sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
script:
  - bundle install
  - bundle exec rake
addons:
  apt:
    packages:
      - libonig-dev
cache:
  directories:
    - /home/travis/.rvm/
    - tmp/*/jq_core/*/tmp/*/ports/jq/1.6/
