language: ruby
rvm:
- 2.0.0
before_script:
- wget http://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.gz
- tar xf bison-3.0.2.tar.gz
- cd bison-3.0.2
- ./configure
- make
- sudo make install
- sudo apt-get install flex libonig2 libonig-dev
- gem install bonsai
- git clone https://github.com/stedolan/jq.git
- cd jq
- autoreconf -i
- ./configure --enable-shared
- make
- sudo make install
- sudo ldconfig
- cd ..
script:
- bundle install
- bundle exec rake
